changelog:
  exclude:
    labels:
      - ignore-for-release
      - bot
  categories:
    - title: Bug fixes 🐛
      labels:
        - bug
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: New Features 🎉
      labels:
        - enhancement
    - title: Tests 💯
      labels:
        - "test"
    - title: Documentation 📄
      labels:
        - "documentation"